// This file is @generated by prost-build.
/// 聊天测试请求
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChatTestBRequest {
    #[prost(string, tag = "1")]
    pub content: ::prost::alloc::string::String,
}
/// 聊天测试响应
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChatTestBResponse {
    #[prost(string, tag = "1")]
    pub content: ::prost::alloc::string::String,
}
