// This file is @generated by prost-build.
/// 服务器配置信息
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerConfig {
    /// 服务器ID
    #[prost(uint32, tag = "1")]
    pub server_id: u32,
    /// 服务器类型
    #[prost(string, tag = "2")]
    pub server_type: ::prost::alloc::string::String,
    /// 后端连接地址
    #[prost(string, tag = "3")]
    pub back_host: ::prost::alloc::string::String,
    /// 后端TCP端口
    #[prost(uint32, tag = "4")]
    pub back_tcp_port: u32,
}
/// 节点注册请求 (继承SerialMessage)
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NodeRegisterBRequest {
    /// 消息ID (从SerialMessage继承)
    #[prost(uint32, tag = "1")]
    pub msg_unique_id: u32,
    /// 客户端令牌
    #[prost(string, tag = "2")]
    pub client_token: ::prost::alloc::string::String,
    /// 服务器配置
    #[prost(message, optional, tag = "3")]
    pub server_config: ::core::option::Option<ServerConfig>,
}
/// 节点注册响应 (继承SerialMessage)
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NodeRegisterBResponse {
    /// 消息ID (从SerialMessage继承)
    #[prost(uint32, tag = "1")]
    pub msg_unique_id: u32,
    /// 服务器列表
    #[prost(message, repeated, tag = "2")]
    pub server_list: ::prost::alloc::vec::Vec<ServerConfig>,
}
/// 节点连接请求 (继承SerialMessage)
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NodeConnectBRequest {
    /// 消息ID (从SerialMessage继承)
    #[prost(uint32, tag = "1")]
    pub msg_unique_id: u32,
    /// 客户端令牌
    #[prost(string, tag = "2")]
    pub client_token: ::prost::alloc::string::String,
    /// 服务器配置
    #[prost(message, optional, tag = "3")]
    pub server_config: ::core::option::Option<ServerConfig>,
}
/// 节点连接响应 (继承SerialMessage)
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NodeConnectBResponse {
    /// 消息ID (从SerialMessage继承)
    #[prost(uint32, tag = "1")]
    pub msg_unique_id: u32,
    /// 服务器配置
    #[prost(message, optional, tag = "2")]
    pub server_config: ::core::option::Option<ServerConfig>,
}
/// 节点注册通知
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NodeRegisterBNotify {
    /// 服务器配置
    #[prost(message, optional, tag = "1")]
    pub server_config: ::core::option::Option<ServerConfig>,
}
/// RPC消息转发请求（前端）
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RpcMessageFRequest {
    /// 消息唯一ID
    #[prost(uint32, tag = "1")]
    pub msg_unique_id: u32,
    /// 目标服务器类型
    #[prost(string, tag = "2")]
    pub server_type: ::prost::alloc::string::String,
    /// 消息ID
    #[prost(uint32, tag = "3")]
    pub msg_id: u32,
    /// 消息内容（字节数组）
    #[prost(bytes = "vec", tag = "4")]
    pub message: ::prost::alloc::vec::Vec<u8>,
}
/// RPC消息转发响应（前端）
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RpcMessageFResponse {
    /// 消息唯一ID
    #[prost(uint32, tag = "1")]
    pub msg_unique_id: u32,
    /// 消息ID
    #[prost(uint32, tag = "2")]
    pub msg_id: u32,
    /// 消息内容（字节数组）
    #[prost(bytes = "vec", tag = "3")]
    pub message: ::prost::alloc::vec::Vec<u8>,
}
/// RPC消息转发通知（前端） - 不需要响应
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RpcMessageFNotify {
    /// 目标服务器类型
    #[prost(string, tag = "1")]
    pub server_type: ::prost::alloc::string::String,
    /// 消息ID
    #[prost(uint32, tag = "2")]
    pub msg_id: u32,
    /// 消息内容（字节数组）
    #[prost(bytes = "vec", tag = "3")]
    pub message: ::prost::alloc::vec::Vec<u8>,
}
/// RPC消息转发请求（后端）
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RpcForwardMessageBRequest {
    /// 消息唯一ID
    #[prost(uint32, tag = "1")]
    pub msg_unique_id: u32,
    /// 前端会话ID
    #[prost(uint64, tag = "2")]
    pub front_session_id: u64,
    /// 元数据
    #[prost(map = "string, int32", tag = "3")]
    pub meta: ::std::collections::HashMap<::prost::alloc::string::String, i32>,
    /// 消息ID
    #[prost(uint32, tag = "4")]
    pub msg_id: u32,
    /// 消息内容（字节数组）
    #[prost(bytes = "vec", tag = "5")]
    pub message: ::prost::alloc::vec::Vec<u8>,
}
/// RPC消息转发响应（后端）
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RpcForwardMessageBResponse {
    /// 消息唯一ID
    #[prost(uint32, tag = "1")]
    pub msg_unique_id: u32,
    /// 前端会话ID
    #[prost(uint64, tag = "2")]
    pub front_session_id: u64,
    /// 元数据
    #[prost(map = "string, int32", tag = "3")]
    pub meta: ::std::collections::HashMap<::prost::alloc::string::String, i32>,
    /// 消息ID
    #[prost(uint32, tag = "4")]
    pub msg_id: u32,
    /// 消息内容（字节数组）
    #[prost(bytes = "vec", tag = "5")]
    pub message: ::prost::alloc::vec::Vec<u8>,
}
/// RPC消息转发通知（后端） - 不需要响应
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RpcForwardMessageBNotify {
    /// 消息ID
    #[prost(uint32, tag = "1")]
    pub msg_id: u32,
    /// 前端会话ID
    #[prost(uint64, tag = "2")]
    pub front_session_id: u64,
    /// 元数据
    #[prost(map = "string, int32", tag = "3")]
    pub meta: ::std::collections::HashMap<::prost::alloc::string::String, i32>,
    /// 消息内容（字节数组）
    #[prost(bytes = "vec", tag = "4")]
    pub message: ::prost::alloc::vec::Vec<u8>,
}
