// This file is @generated by prost-build.
/// 基础消息（空消息）
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BaseMessage {}
/// 带序列号的消息
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SerialMessage {
    /// 消息ID
    #[prost(uint32, tag = "1")]
    pub msg_unique_id: u32,
}
