// This file is @generated by prost-build.
/// Login request from front (F suffix for front messages)
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LoginFRequest {
    #[prost(string, tag = "1")]
    pub token: ::prost::alloc::string::String,
}
/// Login response
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LoginFResponse {
    #[prost(uint64, tag = "1")]
    pub player_id: u64,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
}
